version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: myuser
      POSTGRES_DB: mydb
    ports:
      - "5432:5432" #postrgress sql traffic
    volumes:
      - pgdata:/var/lib/postgresql/data

  testdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: myuser
      POSTGRES_DB: testdb
    ports:
    - "5433:5432" #cant have the same as the db
    volumes:
      - pgdatatest:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://myuser:example@db:5432/mydb?sslmode=disable
  adminer:
    image: adminer
    restart: always
    ports:
      - "9090:8080"

volumes:
  pgdata:
  pgdatatest:
